### PR TITLE
Add ability to include metadata on every event

### PR DESCRIPTION
**Pull request by skylerkatz**
I find myself wanting to include some additional data to every event, even though the data is not entirely related to the event itself.

For example, in a `Middleware` I generate a unique `request_id` and I want that included in every event. I also want to include the current `Team` that the authenticated user is making the request in.

The implementation follows very closely to the way Laravel handles this in their `Queue::createPayloadUsing()` function.

I also added some docs, but not sure if this deserves its own page, vs somewhere else on an existing page.

### CODE REVIEW

**Comment by inxilpro** [comment]
I love this, and definitely want something like this in Verbs. My one question is: do we want metadata to just be a plain array, or do we want to use a collection or bespoke `Metadata` class to provide some convenience methods?

**Comment by skylerkatz** [comment]
I figured a basic array was the easiest thing without overcomplicating it. A collection might be nice as well. If we did a full class, maybe it makes sense to put a second column on the event table for metadata and then we can use a custom eloquent cast.

**Comment by DanielCoulbourne** [comment]
Just throwing some unstructured thoughts out there:

-  I think I favor a 2nd column for metadata
- I think I prefer some knowable structure for metadata. Thus far almost everything you do in a `handle()` method is typed, so it's very hard to reference things that might not exist. I'm pretty into this as it makes me feel a lot safer replaying events if the classes are at least statically valid. Arrays scare me because I can envision adding keys to that array over time, getting out of sync with old events, and eventually getting to an un-replayable situation.
- This plays into a broader conversation @joshhanley @inxilpro and I have been having sort of disjointedly about event versioning #21

**Comment by inxilpro** [comment]
So I could see doing kinda the best of both worlds. We could introduce a `Metadata` class that looks something like:

```php
class Metadata
{
  protected Collection $extra;
  
  public function __construct(array $data = [])
  {
    // 1. Populate any properties that exist using our serializer
    // 2. Push remaining data into $this->extra
  }
  
  public function __get(string $name)
  {
    return $this->extra->get($name);
  }
  
  public function __set(string $name, $value): void
  {
    $this->extra->put($name, $value);
  }
  
  public function __isset(string $name): bool
  {
    return $this->extra->has($name);
  }
}
```

And by default we would populate `$event->metadata` with an instance of that class. Then we could introduce a new configuration that's like `verbs.metdata_class` that lets you set a custom metadata subclass that has typed properties. Something like:

```php
namespace App\Events\Support;

class Metadata extends \Verbs\Metadata
{
  public ?string $user_agent = null;
  
  public ?string $ip_address = null;
  
  public ?int $active_user_id = null;
}
```

And then in your config you'd set `verbs.metdata_class` to `App\Events\Support\Metadata`.

Once that's all hooked up, you could just typehint the `Metadata` class of your choice inside the event lifecycle methods.

```php
public function handle(App\Events\Support\Metadata $metadata) {
  // Now I have my typed metadata object
}
```

And Verbs could handle the DI for you. But if you don't want/need a custom metadata object, you could just type hint the base class and it'd still work.

The upside of this is that a package could rely on metadata always being there without having to know its type ahead of time. A package could just dump values into the metadata payload, and if the end user wanted to access them with type safety, all they would have to do is add properties to their custom class.

**Comment by skylerkatz** [comment]
I really like that approach.

The `EventStore::createMetadataUsing()` function could look something like

```php
EventStore::createMetadataUsing(function (string $event_class, App\Support\Metadata $metadata) {
    $metadata->request_id = (string) Str::uuid();

    return $metadata;
});
```

So you could still sprinkle `EventStore::createMetadataUsing()` throughout the codebase or third party packages.

**Comment by inxilpro** [comment]
Yeah, that's cool. We could definitely support type-hinting either version in the `createMetadataUsing` callback, too.

What's your thinking for wanting the event class in the callback? I would think that anything that's event-specific would live in the event, right? I would think that any global callbacks should only apply global metadata…

**Comment by inxilpro** [comment]
I think we're pretty good. @skylerkatz — you want to take a stab at switching to a class-based approach? I think for the first version we could skip the custom DI stuff, and just know that we want to add that eventually.

**Comment by skylerkatz** [comment]
I think we are just on the "needs to implement stage". Which I plan on working on this week.

**Comment by skylerkatz** [comment]
@inxilpro I pushed up an initial implementation at a `Metadata` class, but I don't love it.

I think it may just be an organization thing, but would love your thoughts on it.

**Review by inxilpro — APPROVED** [review]
I think this is a good approach.

**Pull request merged**
